### ISSUE TITLE
OSS putObject 1.5.2 有一定概率出现签名错误.

### ISSUE THREAD

**Issue by vilic** [aliyun-UED/aliyun-sdk-js#18]
```ts
export class FileStore {
    constructor(public bucket: string) { }
    
    writeFile(key: string, data: string|Buffer): ThenFail<void> {
        console.log(`uploading file "${key}" (${data.length}bytes)...`);
    
        return ThenFail
            .invoke<any>(oss, 'putObject', {
                Bucket: this.bucket,
                Key: key,
                Body: data
            })
            .then(() => console.log(`completed uploading file "${key}".`));
    }
}
```

**Comment by chylvina** [comment]
你好，是对特定的文件吗？

**Comment by vilic** [comment]
不是的, 音频文件和文本文件都出现过. 有时第二次就好了.

**Comment by chylvina** [comment]
昨天 oss 有热升级，请再试一下会不会重现此问题，便于我们排查，谢谢！

**Comment by vilic** [comment]
好的, 我留意一下. FYI, 之前我们用的 1.5.0 的时候也有这个情况.

**Comment by vilic** [comment]
还是有这个问题.

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\services\oss.js:151:37)
    at Request.callListeners (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:113:20)
    at Request.callListeners (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:114:16)
    at Request.emit (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:81:10)
    at Request.emit (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:389:14)
    at Request.transition (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:52:12)
    at AcceptorStateMachine.runTo (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:17:12)
    at C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:29:10
    at Request.<anonymous> (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:58:9)
    at Request.<anonymous> (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:391:12)
    at Request.callListeners (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:90:20)
    at Request.callListeners (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:114:16)
    at Request.emit (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\sequential_executor.js:81:10)
    at Request.emit (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:389:14)
    at Request.transition (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:52:12)
    at AcceptorStateMachine.runTo (C:\Server\zm-chat\server\node_modules\aliyun-sdk\lib\request.js:17:12)
```

**Comment by vilic** [comment]
另外这个问题似乎是程序跑了一段时间才会出现的.

**Comment by chylvina** [comment]
好的我看一下

**Comment by vilic** [comment]
这个不知道有没有帮助:

```
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  headers: 
   { date: 'Sun, 02 Aug 2015 02:44:31 GMT',
     'content-type': 'application/xml',
     'content-length': '1131',
     connection: 'close',
     server: 'AliyunOSS',
     'x-oss-request-id': '55BD840F9C9E589D0DF62371' },
  time: Sun Aug 02 2015 10:44:31 GMT+0800 (China Standard Time),
  statusCode: 403,
  retryable: false }
```

是在同时上传若干个文件的时候发生的, 不过对了一下 Content-Length, 传的文件应该都比 1131 大很多, 估计是上传不完整.

但是现在都有重试 3 次, 依然是这样, 重新启动 node 进程后, 又可以了.

这个问题卡着我们的一个服务上线, 希望能尽快解决. 需要提供什么额外的信息我可以尝试帮忙获取.

**Comment by vilic** [comment]
哦反应过来 Content-Length 是 response 的...

**Comment by chylvina** [comment]
hi，这句话是什么意思？

发自我的 iPhone

**Comment by vilic** [comment]
没囧, 可以忽略, 开始我以为其中得 content-length 和我上传的文件长度不符, 然后发现应该是 response content length, 脑抽了一下.

**Comment by chylvina** [comment]
好的，你反馈的这个问题无法重现，所以很难排查。而且其他开发者也没有同样问题，所以你能否看看是不是代码其他地方的问题？

发自我的 iPhone

**Comment by vilic** [comment]
嗯这个确实挺麻烦. 但是目前我调用到这个方法的地方除了传入后不可能再改变的字符串外, 都是:

```
return ThenFail
    .invoke<Buffer>(FS, 'readFile', from)
    .then(data => this.writeFile(toKey, data));
```

应该也是读出后就不可能再改变的了. writeFile 方法中第一句 log 打印也都是正常的.

**Comment by xiong-liang** [comment]
你这语法是 php ?

发自我的 iPhone

**Comment by vilic** [comment]
是 TypeScript... 囧...

**Comment by vilic** [comment]
我暂时移除了 API 定义中 OSS 下 putObject 的 ContentMD5 一项, 想问下这样可行吗?

**Comment by chylvina** [comment]
可行，就是不太安全。


发自我的 iPhone

**Comment by vilic** [comment]
:+1: 了解, 谢谢啦~

**Comment by vilic** [comment]
表示删除后还是会有问题出现 O.O. 不过目前出现都是在直接上传的 json 字符串上. 同样重启进程后恢复正常.

**Comment by chylvina** [comment]
签名和md5没关系的

发自我的 iPhone

**Comment by vilic** [comment]
囧,,, 话说有什么是我可以测试来提供信息的么. 这边出现情况还是挺频繁的.

**Comment by xiong-liang** [comment]
启动时加上 DEBUG=1 ，然后把 log 记下来看看

发自我的 iPhone

**Comment by vilic** [comment]
好的~

**Comment by vilic** [comment]
Here's the log before signature error. (Retried for 3 times by my logic.)

```
uploading file "x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json" (1097353bytes)...
emit validate
emit build
emit afterBuild
emit sign
----------- sign string start -----------
PUT

application/octet-stream
Fri, 07 Aug 2015 14:16:37 GMT
/zm-chat-lessons/x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
----------- sign string end -----------
emit send
-------- HttpRequest Start: --------
method: PUT
path: /x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
headers:
User-Agent : aliyun-sdk-nodejs/1.5.2(win32/6.3.9600/x64;v0.12.6)
Content-Type : application/octet-stream
Content-Length : 1097353
Host : zm-chat-slides.oss-cn-hangzhou-internal.aliyuncs.com
Date : Fri, 07 Aug 2015 14:16:37 GMT
Authorization : OSS m0YgKExwRJZU0WlM:IQeCEOPL9534I5oYh0PuAHLa7gA=
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpHeaders
emit httpData
emit httpDownloadProgress
emit httpDone
emit validateResponse
emit extractError
emit retry
emit afterRetry
emit error
emit complete
emit validate
emit build
emit afterBuild
emit sign
----------- sign string start -----------
PUT

application/octet-stream
Fri, 07 Aug 2015 14:16:37 GMT
/zm-chat-lessons/x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
----------- sign string end -----------
emit send
-------- HttpRequest Start: --------
method: PUT
path: /x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
headers:
User-Agent : aliyun-sdk-nodejs/1.5.2(win32/6.3.9600/x64;v0.12.6)
Content-Type : application/octet-stream
Content-Length : 1097353
Host : zm-chat-slides.oss-cn-hangzhou-internal.aliyuncs.com
Date : Fri, 07 Aug 2015 14:16:37 GMT
Authorization : OSS m0YgKExwRJZU0WlM:IQeCEOPL9534I5oYh0PuAHLa7gA=
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpHeaders
emit httpData
emit httpDownloadProgress
emit httpDone
emit validateResponse
emit extractError
emit retry
emit afterRetry
emit error
emit complete
emit validate
emit build
emit afterBuild
emit sign
----------- sign string start -----------
PUT

application/octet-stream
Fri, 07 Aug 2015 14:16:37 GMT
/zm-chat-lessons/x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
----------- sign string end -----------
emit send
-------- HttpRequest Start: --------
method: PUT
path: /x0XsFhoAQkW890l8PrfSi6MA0GaDUvBM/events.json
headers:
User-Agent : aliyun-sdk-nodejs/1.5.2(win32/6.3.9600/x64;v0.12.6)
Content-Type : application/octet-stream
Content-Length : 1097353
Host : zm-chat-slides.oss-cn-hangzhou-internal.aliyuncs.com
Date : Fri, 07 Aug 2015 14:16:37 GMT
Authorization : OSS m0YgKExwRJZU0WlM:IQeCEOPL9534I5oYh0PuAHLa7gA=
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpHeaders
emit httpData
emit httpDownloadProgress
emit httpDone
emit validateResponse
emit extractError
emit retry
emit afterRetry
emit error
emit complete
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
emit httpUploadProgress
```

**Comment by vilic** [comment]
I noticed some mismatch with bucket name and host. `zm-chat-lessons` is going with host `zm-chat-slides.oss-cn-hangzhou-internal.aliyuncs.com`.

**Comment by chylvina** [comment]
Latest version 1.5.7 may resolve your problem. Thanks for your feedback.

**Comment by vilic** [comment]
Great to know, thanks! :D
