### ISSUE TITLE
TypeError: sts.assumeRole is not a function

### ISSUE THREAD

**Issue by atrun** [aliyun-UED/aliyun-sdk-js#182]
TypeError: sts.assumeRole is not a function
    at d:\H5\vh5\server.js:64:7
    at Layer.handle [as handle_request] (d:\H5\vh5\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\H5\vh5\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\H5\vh5\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\H5\vh5\node_modules\express\lib\router\layer.js:95:5)
    at d:\H5\vh5\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\H5\vh5\node_modules\express\lib\router\index.js:330:12)
    at next (d:\H5\vh5\node_modules\express\lib\router\index.js:271:10)
    at SendStream.error (d:\H5\vh5\node_modules\serve-static\index.js:120:7)
    at SendStream.emit (events.js:189:13)

**Comment by atrun** [comment]
STS坑多呀，但还是解决了。

改了两处就可以用了。

apiVersion: '2015-04-01'


// 构造AssumeRole请求  
sts.assumeRole({
    Action: 'AssumeRole', 
       RoleArn: roleArn,

要加“Action”

**Comment by xuoutput** [comment]
来考古, 2023 依旧有这个问题
```
TypeError: sts.assumeRole is not a function<
```
