### ISSUE TITLE
1.6.5的客户端版本不能使用oss-js-upload

### ISSUE THREAD

**Issue by zhaoyao91** [aliyun-UED/aliyun-sdk-js#46]
使用1.6.2版本没有问题。

Exception in delivering result of invoking 'ALYSTSMethods.getToken': MODULE_NOT_FOUND: Could not find API configuration oss-2013-10-15
    at s (http://127.0.0.1:3000/aliyun-sdk.js:1:156)
    at s (http://127.0.0.1:3000/aliyun-sdk.js:1:122)
    at http://127.0.0.1:3000/aliyun-sdk.js:1:313
    at Function.defineServiceApi (http://127.0.0.1:3000/aliyun-sdk.js:2619:31)
    at getLatestServiceClass (http://127.0.0.1:3000/aliyun-sdk.js:2320:19)
    at loadServiceClass (http://127.0.0.1:3000/aliyun-sdk.js:2311:19)
    at Service [as constructor] (http://127.0.0.1:3000/aliyun-sdk.js:2290:29)
    at new features.constructor (http://127.0.0.1:3000/aliyun-sdk.js:5218:24)
    at new OssUpload (http://127.0.0.1:3000/oss-js-upload.js:53:18)
    at http://127.0.0.1:3000/app/client/pages/test-oss.jsx?72b01a828b6073bfbd616a58558c2153b275772e:28:29

**Comment by chylvina** [comment]
试一下 1.7.5 刚发布的

**Comment by zhaoyao91** [comment]
ok，可用。

**Comment by chylvina** [comment]
好的多谢
