### ISSUE TITLE
string stream　化上传错误．

### ISSUE THREAD

**Issue by xingchch** [aliyun-UED/aliyun-sdk-js#72]
node -v
v1.12.5

"dependencies": {
"aliyun-oss-upload-stream": "1.2.3",
"aliyun-sdk":"1.7.8",
"sqlite3": "3.1.0",
"winston": "2.2.0",
"iconv-lite":"0.4.12",
"url":"^0.10.3"
},
字符串ｓｔｒｉｎｇ化上传．

```
try{
                var s = new stream.Readable();//"this is test";
                s._read = function noop(){};
                s.push(content);
                s.push(null);
                s.pipe(upload);

            }

```
part 和uploaded事件依次触发，但随即报以下错误：

if (this._hardError) throw err;
^
200: null
at Request.extractError (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/services/oss.js:151:37)
at Request.callListeners (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)
at Request.callListeners (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/sequential_executor.js:114:16)
at Request.emit (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/sequential_executor.js:81:10)
at Request.emit (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:389:14)
at Request.transition (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:52:12)
at AcceptorStateMachine.runTo (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:17:12)
at /home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:29:10
at Request.transition (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:66:7)
at AcceptorStateMachine.runTo (/home/xingchch/homepage/parser/node_modules/aliyun-sdk/lib/request.js:17:12)

**Comment by xingchch** [comment]
是由于我的回调函数发生了错误．关闭之．
