### ISSUE TITLE
ECS呼叫完createInstance後，再呼叫describeInstanceStatus就發生錯誤!!!

### ISSUE THREAD

**Issue by tierra18g** [aliyun-UED/aliyun-sdk-js#88]
Hi All,

詳細情況說明如下:
1. 先呼叫 createInstance，成功後(雲服務器可看到)，狀態為 已停止 。
2. 之後再呼叫 describeInstanceStatus 時，就會發生Exception，程式執行中斷.

程式樣本如下:

```
ALY = require('aliyun-sdk/index.js');  
AliECSObj = new ALY.ECS({
    accessKeyId: AliCloudServicesAccessKey,
    secretAccessKey: AliCloudServicesSecretKey,
    endpoint: AliCloudServicesEndPoint,
    apiVersion: AliCloudServicesAPIVersion
  }
);

CreateInstanceParameters = {
  RegionId:     AliCloudServicesRegionId,
  ImageId:      AliCloudServicesImageId,
  InstanceType: AliCloudServicesInstanceType,
  SecurityGroupId:  AliCloudServicesSecurityGroupId,
  HostName:     InstanceName,
  InstanceName: InstanceName,
  InternetChargeType: "PayByTraffic",
  VSwitchId:    AliCloudServicesVSwitchId 
};

// Call CreateInstance
AliECSObj.createInstance(CreateInstanceParameters, function(Error, Responses){
  ... 
 });


DescribeInstanceStatusParameters = {
  RegionId:     AliCloudServicesRegionId,
  PageSize:     50
};

// Call DescribeInstanceStatusParameters                                                               
AliECSObj.describeInstanceStatus(DescribeInstanceStatusParameters, function(Error, Responses){    <-- 此步驟執行時，發生錯誤
  ...
  });


錯誤如下: 
```

[root@johnlai-centos7 monitor-uc]#   monitor-uc/node_modules/aliyun-sdk/lib/request.js:99
      if (this._hardError) throw err;
                                 ^
UnknownError: null
    at Object.extractError (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/service_interface/json.js:44:33)
    at Request.extractError (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/service_interface/pop.js:15:31)
    at Request.callListeners (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)
    at Request.emit (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:390:14)
    at Request.transition (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:52:12)
    at AcceptorStateMachine.runTo (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:17:12)
    at /root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/root/PushAgent/monitor-uc/node_modules/aliyun-sdk/lib/request.js:17:12)

```
請問這有解嗎? 是啥問題造成的呢? 
```

 PS: 我使用的Node 版本為 v0.12.7

johnlai

**Comment by chylvina** [comment]
ecs api 需要更新，我后续会更新，谢谢反馈。

**Comment by chylvina** [comment]
reopen

**Comment by chylvina** [comment]
你好，发布 1.9.11 版本，更新了最新的 ecs api，请验证一下，谢谢。
