### ISSUE TITLE
使用ram.json报错

### ISSUE THREAD

**Issue by JasonGao180** [aliyun-UED/aliyun-sdk-js#90]
```
$ browserify -r ram-2015-04-01.json  browser.js > dist/aliyun-sdk.js
Error: Cannot find module 'ram-2015-04-01.json' from '/Users/JasonGao/Desktop/aliyunjs/aliyun-sdk-js'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

其他产品是正常的，例如执行
```
browserify -r sts-2015-04-01.json  browser.js > dist/aliyun-sdk.js
```
没有任何问题

**Comment by chylvina** [comment]
解决了
https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/package.json#L42
